#!/bin/sh
#
# advantech init....
#

case "$1" in
start)
    CPUINFO=`cat /proc/cpuinfo | grep "Serial"`
    echo ${CPUINFO##*:} > /etc/serialID
    if [ -d "/userdata" ];then
        chmod 0777 /userdata 
    fi
    ;;
stop)
    ;;
restart|reload)
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

